/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/app/**/*.{js,jsx,ts,tsx}',
    './src/components/layout/**/*.{js,jsx,ts,tsx}',
    './src/components/sections/**/*.{js,jsx,ts,tsx}',
    './src/components/ui/**/*.{js,jsx,ts,tsx}',
    './src/data/**/*.{js,jsx,ts,tsx}',
    '!./src/components/UploadModal.jsx',
    '!./src/components/UploadModal.css',
    '!./src/i18n/translations.js',
    '!./src/utils/markdown.js',
  ],
  theme: {
    extend: {
      colors: {
        /* ── Acctual palette (14색) ── */
        'paper-white':      '#ffffff',
        'cool-mist':        '#f7fafc',
        'stone-edge':       '#afb0b1',
        'graphite-mute':    '#8d8d8d',
        'charcoal-whisper': '#1e1e1e',
        'midnight-ink':     '#0f0f0f',
        'onyx-button':      '#0d111b',
        'tinted-shadow':    '#242628',
        'invoice-blue':     '#0098f2',
        'magenta-tile':     '#f200ca',
        'iris-glow':        '#6d56fc',
        'wash-sky':         '#cfeafa',
        'wash-lilac':       '#e1e0fc',
        'wash-petal':       '#f6d2f4',

        /* ── Legacy aliases — Phase2 bridge ── */
        primary:           '#0098f2',
        'primary-focus':   '#0098f2',

        ink:               '#0f0f0f',
        body:              '#0f0f0f',
        'body-on-dark':    '#ffffff',
        'body-muted':      '#8d8d8d',
        'ink-muted-80':    '#1e1e1e',
        'ink-muted-48':    '#8d8d8d',
        'divider-soft':    '#afb0b1',
        hairline:          '#afb0b1',
        canvas:            '#f7fafc',
        'canvas-parchment':'#f7fafc',
        'surface-pearl':   '#ffffff',
        'surface-tile-1':  '#0d111b',
        'surface-tile-2':  '#0d111b',
        'surface-tile-3':  '#0d111b',
        'surface-black':   '#000000',
        'surface-chip':    '#afb0b1',
        'on-primary':      '#ffffff',
        'on-dark':         '#ffffff',
      },
      fontSize: {
        /* ── Acctual type scale ── */
        caption:      ['12px', { lineHeight: '1.2' }],
        'body-sm':    ['14px', { lineHeight: '1.43' }],
        body:         ['16px', { lineHeight: '1.5' }],
        subheading:   ['20px', { lineHeight: '1.4',  letterSpacing: '-0.24px' }],
        heading:      ['32px', { lineHeight: '1.25', letterSpacing: '-0.64px' }],
        'heading-lg': ['40px', { lineHeight: '1.21', letterSpacing: '-1.2px' }],
        display:      ['64px', { lineHeight: '1.13', letterSpacing: '-2.4px' }],

        /* ── Legacy aliases — Phase2 bridge ── */
        'nav-link':      ['12px', { lineHeight: '1.0' }],
        'fine-print':    ['12px', { lineHeight: '1.0' }],
        'caption-strong':['14px', { lineHeight: '1.29', fontWeight: '600' }],
        'body-strong':   ['16px', { lineHeight: '1.5',  fontWeight: '600' }],
        tagline:         ['20px', { lineHeight: '1.4' }],
        lead:            ['28px', { lineHeight: '1.25' }],
        'display-md':    ['32px', { lineHeight: '1.25', letterSpacing: '-0.64px' }],
        'display-lg':    ['40px', { lineHeight: '1.21', letterSpacing: '-1.2px' }],
        'hero-display':  ['64px', { lineHeight: '1.13', letterSpacing: '-2.4px' }],
      },
      fontFamily: {
        sans:        ['var(--font-inter)', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        handwritten: ['var(--font-caveat)', 'cursive'],
      },
      spacing: {
        xxs: '4px',
        xs:  '8px',
        sm:  '12px',
        md:  '16px',
        lg:  '24px',
        xl:  '32px',
        xxl: '48px',
        section: '64px',
      },
      borderRadius: {
        none:  '0px',
        xs:    '5px',
        sm:    '8px',
        md:    '11px',
        lg:    '18px',
        input: '12px',
        card:  '20px',
        image: '32px',
        pill:  '100px',
        tag:   '1250px',
        full:  '9999px',
      },
      boxShadow: {
        subtle:  'rgba(0,0,0,0.06) 0px 2.5px 2.5px 0px',
        cta:     'rgb(36,38,40) 0px 0px 0px 1px, rgba(27,28,29,0.48) 0px 1px 2px 0px',
        product: 'rgba(0,0,0,0.06) 0px 2.5px 2.5px 0px',
      },
      backdropBlur:     { nav: '20px' },
      backdropSaturate: { nav: '180%' },
      height: {
        nav:      '44px',
        'sub-nav':'52px',
      },
    },
  },
  plugins: [],
}
