/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/app/**/*.{js,jsx,ts,tsx}',
    './src/components/layout/**/*.{js,jsx,ts,tsx}',
    './src/components/sections/**/*.{js,jsx,ts,tsx}',
    './src/components/ui/**/*.{js,jsx,ts,tsx}',
    './src/data/**/*.{js,jsx,ts,tsx}',
    '!./src/components/UploadModal.jsx',
    '!./src/components/UploadModal.css',
    '!./src/i18n/translations.js',
    '!./src/utils/markdown.js',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0066cc',
        'primary-focus': '#0071e3',
        'primary-on-dark': '#2997ff',
        ink: '#1d1d1f',
        body: '#1d1d1f',
        'body-on-dark': '#ffffff',
        'body-muted': '#cccccc',
        'ink-muted-80': '#333333',
        'ink-muted-48': '#7a7a7a',
        'divider-soft': '#f0f0f0',
        hairline: '#e0e0e0',
        canvas: '#ffffff',
        'canvas-parchment': '#f5f5f7',
        'surface-pearl': '#fafafc',
        'surface-tile-1': '#272729',
        'surface-tile-2': '#2a2a2c',
        'surface-tile-3': '#252527',
        'surface-black': '#000000',
        'surface-chip': '#d2d2d7',
        'on-primary': '#ffffff',
        'on-dark': '#ffffff',
      },
      fontSize: {
        'nav-link': ['12px', { lineHeight: '1.0', letterSpacing: '-0.12px' }],
        caption: ['14px', { lineHeight: '1.43', letterSpacing: '-0.224px' }],
        'caption-strong': ['14px', { lineHeight: '1.29', letterSpacing: '-0.224px', fontWeight: '600' }],
        'fine-print': ['12px', { lineHeight: '1.0', letterSpacing: '-0.12px' }],
        body: ['17px', { lineHeight: '1.47', letterSpacing: '-0.374px' }],
        'body-strong': ['17px', { lineHeight: '1.24', letterSpacing: '-0.374px', fontWeight: '600' }],
        tagline: ['21px', { lineHeight: '1.19', letterSpacing: '0.231px' }],
        lead: ['28px', { lineHeight: '1.14', letterSpacing: '0.196px' }],
        'display-md': ['34px', { lineHeight: '1.47', letterSpacing: '-0.374px' }],
        'display-lg': ['40px', { lineHeight: '1.1', letterSpacing: '0' }],
        'hero-display': ['56px', { lineHeight: '1.07', letterSpacing: '-0.28px' }],
      },
      fontFamily: {
        sans: [
          'SF Pro Display',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Inter',
          'sans-serif',
        ],
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '17px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '80px',
      },
      borderRadius: {
        none: '0px',
        xs: '5px',
        sm: '8px',
        md: '11px',
        lg: '18px',
        pill: '9999px',
        full: '9999px',
      },
      boxShadow: {
        product: 'rgba(0,0,0,0.22) 3px 5px 30px',
      },
      backdropBlur: {
        nav: '20px',
      },
      backdropSaturate: {
        nav: '180%',
      },
      height: {
        nav: '44px',
        'sub-nav': '52px',
      },
    },
  },
  plugins: [],
}
